spring:
  redis:
    host: 192.168.0.111
    port: 6379
ribbon:
  ReadTimeout: 5000
  SocketTimeout: 5000
zuul:
  #全部服务忽略敏感头信息(全部服务都可传递cookie)
  sensitive-headers: 
  routes:
    #自定义规则, 将 /myProduct/product/list -> /product/proudct/list
    myProduct:
      path: /myProduct/**
      serviceId: product
      #获取请求头中的cookie
      sensitiveHeaders:

#    #简洁写法
#    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
management:
  endpoints:
    web:
      exposure:
        include: "*"
