spring:
  application:
    name: order
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
        url: jdbc:mysql://192.168.0.111:3306/weixin_sell?characterEncoding=utf8&useSSL=false
  rabbitmq:
      host: 192.168.0.111
      port: 5672
      username: guest
      password: guest
  redis:
    host: 192.168.0.111
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.sell.order.mapper: debug
pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  pageSizeZero: true
  params: count=countSql
#feign组件的超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
env:
  dev
label:
  release
ORDER:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
